version: '3'
services:

  gitlab:
    image: ${GITLAB_SERVER_IMAGE_NAME}:v0.0.1
    container_name: ${GITLAB_SERVER_CONTAINER_NAME}
    build:
      context: .
      dockerfile: gitlab.dockerfile
    restart: always
    hostname: ${HOSTNAME}
    env_file: 
      - .env
    ports:
      - ${LOCAL_HTTP_PORT}:80
      - ${LOCAL_HTTPS_SSL_PORT}:443
      - ${LOCAL_SSH_PORT}:22
    volumes:
      - ${LOCAL_CONFIG_DIR}:/etc/gitlab
      - ${LOCAL_LOGS_DIR}:/var/log/gitlab
      - ${LOCAL_DATA_DIR}:/var/opt/gitlab
    